Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12.4"
  config.vm.provision :shell, path: "./bootstrap.sh"
  config.vm.provider "virtualbox" do |provider|
    provider.name = "pmtestbench"
    # Adjust those as resources are available
    # provider.memory = 16384
    # provider.cpus = 8
    provider.memory = 8192
    provider.cpus = 6
  end
end

